sudo: required

services: docker

before install:
  - docker-compose up --build -d

script:
  - docker-compose exec --env 'RAILS_ENV=test' my-app-web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' my-app-web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' my-app-web rails test
