sudo: required

services: docker

before install:
  - docker-compose up --build -d
  - echo "$HEROKU_API_KEY" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

script:
  - docker-compose exec --env 'RAILS_ENV=test' my-app-web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' my-app-web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' my-app-web rails test

deploy:
  provider: script
  script:
    docker build -t registry.heroku.com/$HEROKU_APP_NAME/web -f Dockerfile.prod .;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku run --app $HEROKU_APP_NAME rails db:migrate;
  on:
    branch: master